version: '3.8'

services:
  replicate-landmarks-api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - REPLICATE_API_TOKEN=${REPLICATE_API_TOKEN}
    volumes:
      - .:/app
    restart: unless-stopped
